### ISSUE TITLE
YAML parse error on hasura/templates/hpa.yaml

### ISSUE THREAD

**Issue by michaelstiben** [hasura-extra/hasura-extra#186]
Using the autoscaling.targetMemoryUtilizationPercentage in the helm chart version **3.0.0** I got the following error:

```
Error: YAML parse error on hasura/templates/hpa.yaml: error converting YAML to JSON: yaml: line 27: mapping values are not allowed in this context
 
   with helm_release.hasura[0],
   on main.tf line 10, in resource "helm_release" "hasura":
   10: resource "helm_release" "hasura" {
```

The above error was thrown using terraform module for helm chart, so I tried to replicate the error using my local environment with the following command:

`helm template hasura-debug hasura-extra/hasura -f values.yaml --debug`

The result was the same: 

```
Error: YAML parse error on hasura/templates/hpa.yaml: error converting YAML to JSON: yaml: line 27: mapping values are not allowed in this context
helm.go:84: [debug] error converting YAML to JSON: yaml: line 27: mapping values are not allowed in this context
YAML parse error on hasura/templates/hpa.yaml
```

Checking the produced hpa template file looks as follows. Notice that in the metric[1].resource.name value there is a bad behavior in the parser, because it is skipping the new line  between "memory" and "target"

```
---
# Source: hasura/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hasura-distribution
  labels:
    helm.sh/chart: hasura-3.0.0
    app.kubernetes.io/name: hasura
    app.kubernetes.io/instance: hasura-distribution
    app.kubernetes.io/version: "v2.34.0-ce"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hasura-distribution
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memorytarget:
          type: Utilization
          averageUtilization: 80
```

This is the used values.yaml file

```
serviceAccount:
  name: hasura

image:
  tag: "v2.34.0-ce"

resources:
  limits:
    memory: 1024Mi
    cpu: 500m
  requests:
    cpu: 500m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetMemoryUtilizationPercentage: 50


extraEnvVarsCM:
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'view'

v1BooleanNullCollapse: 'true'

secretName: hasura
```

---

My local env:

Ubuntu 22.04
Helm version: version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"} 
Kubernetes client version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:48:26Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Kubernetes server version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.7-eks-4f4795d", GitCommit:"3719c8491f81867f591e895a43b4f5aab4145794", GitTreeState:"clean", BuildDate:"2023-10-20T23:21:04Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

Thanks for you help.
